Add missing deps for openbabel.pybel
Otherwise import openbabel.pybel errors as per the following minimal example:
```
FROM python:slim
RUN pip install openbabel-wheel
# Final line fails; uncomment next line to fix
# RUN apt-get -q update && apt-get install -y --no-install-recommends libxext-dev libxrender-dev
RUN python -c "from openbabel import pybel"
```
which gives:
```
Error: libXrender.so.1: cannot open shared object file: No such file or directory
```
and
```
 Error: libXext.so.6: cannot open shared object file: No such file or directory
```